searches:
  indeed:
    - job: java
      locations: ["Rio de Janeiro, RJ"]
    - job: programador junior
      locations: ["Rio de Janeiro, RJ"]
    - job: desenvolvedor junior
      locations: ["Rio de Janeiro, RJ"]
    # - job: assistente administrativo
    #   locations: ["Rio de Janeiro, RJ"]
  infojob:
    - job: desenvolvedor java
      locations: ["Rio de Janeiro - RJ"]
  linkedin:
    - job: Desenvolvedor Java
      locations: ["Rio de Janeiro, Brasil"]
filters:
  - key: title
    exclude:
      - programming_languages: ["delphi", "c", "c#", "c++", "net", "php", "golang", "go", "swift", "kotlin"]
      - seniorities: ["pleno", "senior", "pl", "sr", "especialista", "specialist", "mid", "midlevel", "ii", "iii", "ll", "lll"]
      - positions: ["lead", "lider", "architect", "arquiteto", "mobile", "seguranca", "principal", "qa", "staff", "diretor", "gerente", "manager"]
      - so: ["android", "ios"]
  - key: description
    exclude:
      - languages: ["english", "ingles avancado", "ingles fluente"]
      - seniorities: ["pleno", "senior", "pl", "sr", "especialista", "specialist", "mid", "midlevel", "ii", "iii", "ll", "lll"]
  - key: description
    full_match: false
    include:
      - programming_languages: ["java", "spring", "javascript", "typescript", "python", "node", "nodejs"]
      # - others: ["ms office", "pacote office", "excel", "planilha", "planilhas", "informatica", "correio", "correios", "linguagem de programacao"]
  - key: company
    exclude:
      - companies: ["netvagas", "bairesdev"]